# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='official_event',
            new_name='is_official_event',
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='content',
            field=models.TextField(blank=True, default='', help_text='All event information.'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='extra_URLs',
            field=models.TextField(blank=True, default='', help_text='Any other website, separate multiple urls  with commas.'),
        ),
    ]
