# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 01:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.bookings.models


class Migration(migrations.Migration):

    replaces = [('bookings', '0001_initial'), ('bookings', '0002_auto_20160624_1549'), ('bookings', '0003_auto_20160626_1448'), ('bookings', '0004_auto_20160626_1656'), ('bookings', '0005_auto_20160626_2348'), ('bookings', '0006_auto_20160903_2333'), ('bookings', '0007_auto_20160909_0001'), ('bookings', '0008_auto_20160912_1656'), ('bookings', '0009_auto_20160913_0051'), ('bookings', '0010_auto_20160914_1654'), ('bookings', '0011_auto_20160924_2301')]

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed'), ('Numbers Unconfirmed', 'Numbers Unconfirmed'), ('Big Booking', 'Big Booking'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('booking_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('facebook', 'Facebook'), ('person', 'In Person'), ('other', 'Other')], default='phone', max_length=50)),
                ('reserved_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('reserved_time', models.TimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=project.bookings.models.get_current_site, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_booking', to='sites.Site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'ordering': ['-reserved_date', 'reserved_time', 'name'],
                'verbose_name_plural': 'bookings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([]),
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['reserved_date', 'reserved_time', 'name'], 'verbose_name_plural': 'bookings'},
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, choices=[('lunch', 'Lunch'), ('afternoon', 'Afternoon'), ('main', 'Main')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('website', 'Online'), ('facebook', 'Facebook Messenger'), ('person', 'In Person'), ('other', 'Other')], default='phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="One phone number only. Put additional numbers in 'notes' if necessary.", max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_method',
            field=models.CharField(choices=[(b'phone', b'Phone'), (b'email', b'Email'), (b'website', b'Online'), (b'facebook', b'Facebook Messenger'), (b'person', b'In Person'), (b'other', b'Other')], default=b'phone', help_text='Only logged in people can see booking method.', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(b'Added', b'Added'), (b'Confirmed', b'Confirmed'), (b'Numbers Confirmed', b'Numbers Confirmed'), (b'Big Booking', b'Big Booking'), (b'Cancelled', b'Cancelled')], default=b'Added', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='hear_choices',
            field=models.CharField(blank=True, choices=[(b'event', b'event'), (b'facebook', b'facebook'), (b'friends', b'friends'), (b'newspaper', b'newspaper'), (b'search', b'search'), (b'other', b'other')], default='', help_text='How did you hear about us?', max_length=56, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hear_other',
            field=models.TextField(blank=True, default='', help_text='Tell us a story about how you heard about us ...', verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='booking',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="One phone number only. Put additional numbers in 'notes' if necessary. We may need to confirm details so be sure to provide a good number.", max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(help_text="One phone number only. Put additional numbers in 'notes' if necessary. We may need to confirm details so be sure to provide a good number.", max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(b'Booked', b'Booked'), (b'Confirmed', b'Confirmed'), (b'Numbers Confirmed', b'Numbers Confirmed'), (b'Big Booking', b'Big Booking'), (b'Cancelled', b'Cancelled')], default=b'Booked', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='busy_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='private_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='area',
            field=models.CharField(choices=[(b'inside', b'Inside'), (b'outside', b'Outside')], default=b'inside', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_time',
            field=models.TimeField(choices=[(datetime.time(12, 0), b'12:00'), (datetime.time(12, 30), b'12:30'), (datetime.time(13, 0), b'13:00'), (datetime.time(13, 30), b'13:30'), (datetime.time(14, 0), b'14:00'), (datetime.time(14, 30), b'14:30'), (datetime.time(15, 0), b'15:00'), (datetime.time(15, 30), b'15:30'), (datetime.time(16, 0), b'16:00'), (datetime.time(16, 30), b'16:30'), (datetime.time(17, 0), b'17:00'), (datetime.time(17, 30), b'17:30'), (datetime.time(18, 0), b'18:00'), (datetime.time(18, 30), b'18:30'), (datetime.time(19, 0), b'19:00'), (datetime.time(19, 30), b'19:30'), (datetime.time(20, 0), b'20:00'), (datetime.time(20, 30), b'20:30'), (datetime.time(21, 0), b'21:00'), (datetime.time(21, 30), b'21:30'), (datetime.time(22, 0), b'22:00'), (datetime.time(22, 30), b'22:30'), (datetime.time(23, 0), b'23:00')], db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='legacy_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_time',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
