# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20170919_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_num', models.PositiveIntegerField(default=0, null=True)),
                ('total_pax', models.PositiveIntegerField(default=0, null=True)),
                ('early_num', models.PositiveIntegerField(default=0, null=True)),
                ('early_pax', models.PositiveIntegerField(default=0, null=True)),
                ('lunch_num', models.PositiveIntegerField(default=0, null=True)),
                ('lunch_pax', models.PositiveIntegerField(default=0, null=True)),
                ('afternoon_num', models.PositiveIntegerField(default=0, null=True)),
                ('afternoon_pax', models.PositiveIntegerField(default=0, null=True)),
                ('main_num', models.PositiveIntegerField(default=0, null=True)),
                ('main_pax', models.PositiveIntegerField(default=0, null=True)),
                ('late_num', models.PositiveIntegerField(default=0, null=True)),
                ('late_pax', models.PositiveIntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, choices=[('early', 'Early'), ('lunch', 'Lunch'), ('afternoon', 'Afternoon'), ('main', 'Main'), ('late', 'Late')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('numbers_confirmed', 'Numbers Confirmed'), ('no_show', 'No Show')], default='booked', max_length=50),
        ),
    ]
