# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 06:36
from __future__ import unicode_literals

from django.db import migrations
import localflavor.au.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20171117_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=localflavor.au.models.AUPhoneNumberField(help_text="One phone number only. Put additional numbers in 'notes' if necessary. We may need to confirm details so be sure to provide a good number.", max_length=20),
        ),
    ]
