# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20171117_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('numbers_confirmed', 'Numbers Confirmed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='booked', max_length=50),
        ),
    ]
