# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180430_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('numbers_confirmed', 'Numbers Confirmed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='booked', max_length=50),
        ),
    ]
