# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20180515_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='reservation_sheet_printed',
            field=models.BooleanField(default=False),
        ),
    ]
