# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20160924_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='area',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('website', 'Online'), ('facebook', 'Facebook Messenger'), ('person', 'In Person'), ('other', 'Other')], default='phone', help_text='Only logged in people can see booking method.', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hear_choices',
            field=models.CharField(blank=True, choices=[('event', 'event'), ('facebook', 'facebook'), ('friends', 'friends'), ('newspaper', 'newspaper'), ('search', 'search'), ('other', 'other')], default='', help_text='How did you hear about us?', max_length=56, verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Numbers Confirmed', 'Numbers Confirmed'), ('Big Booking', 'Big Booking'), ('Cancelled', 'Cancelled')], default='Booked', max_length=50),
        ),
    ]
