# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menutype',
            options={'ordering': ['-publish_at', 'title'], 'verbose_name_plural': 'menus'},
        ),
    ]
