# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields
import project.members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolodex', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name')),
                ('sort_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Surname')),
                ('ref_name', models.CharField(blank=True, default='', max_length=200, verbose_name='First Name')),
                ('notes', models.TextField(blank=True, default='')),
                ('private_notes', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('postcode', models.CharField(blank=True, default='', max_length=16)),
                ('state', models.CharField(blank=True, default='', max_length=16)),
                ('country', models.CharField(blank=True, default='Australia', max_length=16)),
                ('dob', django_date_extensions.fields.ApproximateDateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('email', models.ManyToManyField(to='rolodex.Email')),
                ('phone', models.ManyToManyField(to='rolodex.Phone')),
                ('site', models.ForeignKey(default=project.members.models.get_current_site, on_delete=django.db.models.deletion.PROTECT, related_name='members_member', to='sites.Site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=256)),
                ('valid_from', models.DateField(null=True)),
                ('valid_until', models.DateField(help_text="As the first day of the month following expiry. Eg. Nov 2018 = '1-Dec-2018'", null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('given_tag', models.BooleanField()),
                ('given_card', models.BooleanField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Membership')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paypal', 'paypal'), ('in person', 'in person')], default='paypal', max_length=128)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=1024)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'ordering': ['member__name', 'created_at'],
            },
        ),
    ]
