# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolodex', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_approved_paid', models.BooleanField(default=False)),
                ('approved_payment_method', models.CharField(blank=True, choices=[('paypal', 'paypal'), ('in person', 'in person')], default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name')),
                ('sort_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Surname')),
                ('ref_name', models.CharField(blank=True, default='', max_length=200, verbose_name='First Name')),
                ('notes', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('postcode', models.CharField(blank=True, default='', max_length=16)),
                ('state', models.CharField(blank=True, default='', max_length=16)),
                ('country', models.CharField(blank=True, default='Australia', max_length=16)),
                ('dob', django_date_extensions.fields.ApproximateDateField(blank=True, help_text="We don't like having to ask for this but we children members are differently categorised. Only year, or month and year are required.", null=True)),
                ('payment_method', models.CharField(choices=[('paypal', 'paypal'), ('in person', 'in person')], max_length=255)),
                ('survey_suggestions', models.TextField(blank=True, help_text='Any suggestions you would have for us?', null=True)),
                ('survey_hear', models.TextField(blank=True, help_text='How did you hear about us? Tell us a story.', null=True)),
                ('survey_food', models.TextField(blank=True, help_text='What food, drink or pizza would you like see on our menu? Say as much as you want.', null=True)),
                ('survey_games', models.TextField(blank=True, help_text="What's your favourite game? List as many as you like.", null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email', models.ManyToManyField(to='rolodex.Email')),
                ('phone', models.ManyToManyField(to='rolodex.Phone')),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(max_length=255),
        ),
    ]
