# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_temporarymember_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suburb',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='member_type',
            field=models.CharField(choices=[('family', 'Guild Member Family'), (
                'student', 'Guild Student Member'), ('special', 'other')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('standard', 'Guild Member'), ('family', 'Guild Member Family'), (
                'student', 'Guild Student Member'), ('special', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='state',
            field=models.CharField(max_length=64),
        ),
    ]
