# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_temporarymember_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
