# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170831_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_number',
            new_name='number',
        ),
    ]
