# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170923_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('in person', 'in person'), ('online', 'online')], default='in person', max_length=128),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='approved_payment_method',
            field=models.CharField(blank=True, choices=[('in person', 'in person'), ('online', 'online')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('in person', 'in person'), ('online', 'online')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('in person', 'in person'), ('online', 'online')], default='', max_length=255),
        ),
    ]
