# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170905_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phones',
        ),
    ]
