# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170905_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarymember',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='legacy_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='legacy_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('paypal', 'paypal'), ('in person', 'in person')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, help_text='Kept private.', null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='email',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rolodex.Email'),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='member_type',
            field=models.CharField(blank=True, choices=[('family', 'Guild Member Family'), ('student', 'Guild Student Member'), ('special', 'other')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'paypal'), ('in person', 'in person')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='phone',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rolodex.Phone'),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='ref_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='sort_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
