# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20170910_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
