# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20170910_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='note',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='membership',
            name='special',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('standard', 'Guild Member'), ('family', 'Guild Member Family'), ('student', 'Guild Student Member'), ('special', 'other (please add reason at end)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='member_type',
            field=models.CharField(blank=True, choices=[('family', 'Guild Member Family'), ('student', 'Guild Student Member'), ('special', 'other (please add reason at end)')], default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('member', 'member_type', 'valid_from')]),
        ),
    ]
