# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20170911_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='emails',
            field=models.ManyToManyField(blank=True, to='rolodex.Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phones',
            field=models.ManyToManyField(blank=True, to='rolodex.Phone'),
        ),
    ]
